File for all CV Methods combined so that it runs in a single pipeline

1) To install all required packages for this pipeline, use the `installPackages.sh` script.

2) Imports

In [15]:
#using workaround with rclone
#from google.colab.patches import cv2_imshow #can not use on linux
#from google.colab import drive #can not use on linux

import csv, json, os, math, random, re, sys, statistics
import numpy as np
import pandas as pd
import cv2
import torch, torchvision
import detectron2

from natsort import natsorted, ns
from colorthief import ColorThief
from fer import FER
from PIL import Image
import matplotlib.pyplot as plt
import skimage.io as io #scikit-image

from torch.autograd import Variable as V
from torchvision import transforms as trn
from torch.nn import functional as F
import torchvision.models as models

from detectron2.utils.logger import setup_logger
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer, ColorMode
from detectron2.data import MetadataCatalog, DatasetCatalog

2023-02-11 21:11:41.149419: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
#setup logger for detectron2
setup_logger()

In [39]:
class AgeGender:
  def __init__(self, outputPathImages, outputPathCSV, name):
    self.method = "ageAndGender"
    self.outputPathImages = outputPathImages
    self.outputPathImages = self.outputPathImages.replace("{cv_method}", f"{self.method}")
    self.outputPathCSV = outputPathCSV
    self.outputPathCSV = self.outputPathCSV.replace("{cv_method}", f"{self.method}")
    self.name = name
    print(self.outputPathImages)
    print(self.outputPathCSV)

    # Defined the model files
    self.FACE_PROTO = "./models/opencv_face_detector.pbtxt"
    self.FACE_MODEL = "./models/opencv_face_detector_uint8.pb"
    self.AGE_PROTO = "./models/age_deploy.prototxt"
    self.AGE_MODEL = "./models/age_net.caffemodel"
    self.GENDER_PROTO = "./models/gender_deploy.prototxt"
    self.GENDER_MODEL = "./models/gender_net.caffemodel"

    # Load network
    self.FACE_NET = cv2.dnn.readNet(self.FACE_MODEL, self.FACE_PROTO)
    self.AGE_NET = cv2.dnn.readNet(self.AGE_MODEL, self.AGE_PROTO)
    self.GENDER_NET = cv2.dnn.readNet(self.GENDER_MODEL, self.GENDER_PROTO)

    self.MODEL_MEAN_VALUES = (78.4263377603, 87.7689143744, 114.895847746)
    self.AGE_LIST = ["(0-2)", "(4-6)", "(8-12)", "(15-20)", "(25-32)", "(38-43)", "(48-53)", "(60-100)"]
    self.GENDER_LIST = ["Male", "Female"]

    self.box_padding = 20

    self.frameName = []
    self.person = []
    self.boxFace = []
    self.gen = []
    self.gender_conf = []
    self.ages = []
    self.age_conf = []

  def get_face_box (self, net, frame, conf_threshold = 0.5):
    frame_copy = frame.copy()
    frame_height = frame_copy.shape[0]
    frame_width = frame_copy.shape[1]
    blob = cv2.dnn.blobFromImage(frame_copy, 1.0, (300, 300), [104, 117, 123], True, False)

    net.setInput(blob)
    detections = net.forward()
    boxes = []

    for i in range(detections.shape[2]):
      confidence = detections[0, 0, i, 2]

      if confidence > conf_threshold:
        x1 = int(detections[0, 0, i, 3] * frame_width)
        y1 = int(detections[0, 0, i, 4] * frame_height)
        x2 = int(detections[0, 0, i, 5] * frame_width)
        y2 = int(detections[0, 0, i, 6] * frame_height)
        boxes.append([x1, y1, x2, y2])
        cv2.rectangle(frame_copy, (x1, y1), (x2, y2), (0, 255, 0), int(round(frame_height / 150)), 8)

    return frame_copy, boxes

  def handleNextImage (self, fileName, image):
    resized_image = cv2.resize(image, (640, 480))

    frame = resized_image.copy()
    frame_face, boxes = self.get_face_box(self.FACE_NET, frame)

    count = 0
    for box in boxes:
      self.frameName.append(fileName)
      self.person.append(count)
      self.boxFace.append(box)
      face = frame[max(0, box[1] - self.box_padding):min(box[3] + self.box_padding, frame.shape[0] - 1), \
        max(0, box[0] - self.box_padding):min(box[2] + self.box_padding, frame.shape[1] - 1)]

      blob = cv2.dnn.blobFromImage(face, 1.0, (227, 227), self.MODEL_MEAN_VALUES, swapRB = False)
      self.GENDER_NET.setInput(blob)
      gender_predictions = self.GENDER_NET.forward()
      gender = self.GENDER_LIST[gender_predictions[0].argmax()]
      self.gen.append(gender)
      self.gender_conf.append(gender_predictions[0].max())

      self.AGE_NET.setInput(blob)
      age_predictions = self.AGE_NET.forward()
      age = self.AGE_LIST[age_predictions[0].argmax()]
      self.ages.append(age)
      self.age_conf.append(age_predictions[0].max())

      label = "{},{}".format(gender, age)
      cv2.putText(frame_face, label, (box[0], box[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2, cv2.LINE_AA)
      cv2.putText(frame_face, str(count), (box[0] + 2, box[1] + 15), cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),1,cv2.LINE_AA, )

      count += 1

    #only saves an image if age/gender was found
    if len(boxes) > 0:
      cv2.resize(frame_face, (640, 480))
      cv2.imwrite(self.outputPathImages + fileName, frame_face)

  def dataToCSV(self):
    if len(self.frameName) > 0:
      df = pd.DataFrame(list(zip(self.frameName, self.person, self.boxFace, self.gen, self.gender_conf, self.ages, self.age_conf)))
      df.columns = ['Name', 'person', 'box', 'gender', 'gender_conf', 'age', 'age_conf']
      df.to_csv(f"{self.outputPathCSV}{self.name}.csv")

In [42]:
import re,json
assetsList = os.listdir("./assets/")

#check the content size of all assets for processingTime

#build folder structure for input/ouput
#put images in folders

configList = open("./config.json", "rb")
config = json.load(configList)
print(config[0]["inputPath"])

for game in config:
  #init detection classes here
  ageGender = AgeGender(game["outputPathImage"], game["outputPathCSV"], game["name"])

  imagesList = os.listdir(game["inputPath"])
  #report length
  for imageName in imagesList:
    #load image with cv2
    image = cv2.imread(f"{game['inputPath']}{imageName}")
    #feed image per image to instance methods
    #image like objectDetection must be saved for each image
    ageGender.handleNextImage(imageName, image)
    print(imageName)
  
  #save data as csv
  #generate color bars
  ageGender.dataToCSV()

  #processing time report with each picture

./assets/Die_Siedler3/
./output/ageAndGender/Die_Siedler3/
./output/ageAndGender/
siedler_frame_90.jpg
siedler_frame_120.jpg
siedler_frame_30.jpg
[[[ 42  16  13]
  [ 44  17  14]
  [ 46  18  16]
  ...
  [ 76 112 128]
  [ 70 108 120]
  [ 82 119 134]]

 [[ 36  12   9]
  [ 43  17  13]
  [ 41  16  11]
  ...
  [ 75 111 126]
  [ 73 108 123]
  [ 74 112 125]]

 [[ 40  16  12]
  [ 44  16  13]
  [ 46  17  14]
  ...
  [ 66 100 115]
  [ 70 109 123]
  [ 69 104 118]]

 ...

 [[ 20  15  16]
  [ 11   7   8]
  [ 13   9  10]
  ...
  [ 18  14  15]
  [ 17  15  15]
  [ 21  19  19]]

 [[ 13   9   8]
  [ 14  10   8]
  [ 21  16  16]
  ...
  [ 15  13  13]
  [ 17  15  15]
  [ 19  19  19]]

 [[ 17  13  14]
  [ 12   7   6]
  [ 17  11  12]
  ...
  [ 18  15  15]
  [ 15  13  13]
  [ 17  13  13]]]
Trump.jpeg
siedler_frame_60.jpg
siedler_frame_0.jpg
./output/{cv_method}/Diablo2/
./output/{cv_method}/
[[[220 214 195]
  [220 214 195]
  [220 214 195]
  ...
  [216 210 205]
  [216 210 205]
  [216 210 205]]

 [[220 214 195]


OSError: Cannot save file into a non-existent directory: 'output/{cv_method}'